server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

#hibernate란? SQL을 직접 사용하지 않고 메서드만 쿼리를 사용하게 하는 라이브러리
#hibernate 기술을 쉽게 사용하게 해주는 라이브러리가 JPA
#ddl-auto: create는 서버 실행할 때마다 테이블을 삭제하고 새로 만드는 설정
#ddl-auto: nune은 서버 실행시 마다 아무것도 하지 않는 옵션
#ddl-auto:update 는 필드 수정시에 필요한 옵션 (필드 삭제하려면 DB에서 직접하기!)
spring:
  datasource:
      url: jdbc:mariadb://localhost:3306/greendb
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  output:
    ansi:
      enabled: always